base_model: meta-llama/Llama-3.2-1B-Instruct
load_in_4bit: true
adapter: lora
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj

datasets:
  - path: knkarthick/samsum
    cache_dir: data/datasets
    field_map:
      input: dialogue
      output: summary
    type: completion

sequence_len: 512
sample_packing: true
output_dir: ./outputs/qlora-run

num_epochs: 2
micro_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2e-4
optimizer: adamw_8bit

bf16: auto
gradient_checkpointing: true

logging:
  wandb: true
  wandb_name: Axolotl_single_gpu_qlora_run
  wandb_project: llama3_samsum
  wandb_entity: hf-internal-testing
  wandb_watch: all
  wandb_log_model: checkpoint

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

strict: false
